name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    uses: KeibaAI-developer/library-workflow/.github/workflows/ci.yml@main
    with:
      package_name: auto_git_push
      repo_name: auto-git-push
